name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build static site
        run: echo "No build needed for static HTML"

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: . 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
